infrastructure tests

diff --git a/test/manifest/test-simple-mtls.yml b/test/manifest/test-simple-mtls.yml
--- a/test/manifest/test-simple-mtls.yml
+++ b/test/manifest/test-simple-mtls.yml
@@ -20,12 +20,20 @@ spec:
       - name: alpine
         image: alpine:latest
         command: ["/bin/sh", "-c"]
-        args: |
-          echo "Test external connection"
-          wget -qO- -t3 google.fr || exit 1
-          echo "Test connection to nginx service on http port"
-          wget -qO- -T3 nginx.default.svc.cluster.local || exit 1
-          echo "Test connection to nginx service on 8000 port"
-          wget -qO- -T3 nginx-different-port.default.svc.cluster.local:8000 || exit 1
+        args:
+        - |
+          echo "Test external connection";
+          wget -qO- -T3 google.fr > /dev/null 2>&1 || exit 1;
+          echo -e  "\n"
+          echo "Test connection to nginx service on http port";
+          wget -qO- -T3 nginx.default.svc.cluster.local || exit 1;
+          echo -e "\n";
+          echo "Test connection to nginx service on 8000 port";
+          wget -qO- -T3 nginx-different-port.default.svc.cluster.local:8000
+          if [ $? == 0 ]
+          then
+            echo "Error, connection shouldn't have worked";
+            exit 1
+          fi
         ports:
         - containerPort: 80
